"""added all the tables

Revision ID: 5453f4d6ec9f
Revises: 9e511872ac00
Create Date: 2026-09-04 16:38:49.128622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5453f4d6ec9f'
down_revision: Union[str, Sequence[str], None] = '9e511872ac00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commanders',
    sa.Column('commander_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('commander_id')
    )
    op.create_index(op.f('ix_commanders_email'), 'commanders', ['email'], unique=True)
    op.create_table('incident_master',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('incident_number', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('short_description', sa.String(length=1000), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_index(op.f('ix_incident_master_incident_number'), 'incident_master', ['incident_number'], unique=False)
    op.create_index(op.f('ix_incident_master_user_email'), 'incident_master', ['user_email'], unique=False)
    op.create_table('agent_execution',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('agent_name', sa.String(length=150), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('execution_status', sa.String(length=50), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('evaluation_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('judge_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_index(op.f('ix_agent_execution_incident_id'), 'agent_execution', ['incident_id'], unique=False)
    op.create_table('blast_radius',
    sa.Column('blast_radius_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('affected_service', sa.String(length=255), nullable=False),
    sa.Column('affected_component', sa.String(length=255), nullable=False),
    sa.Column('dependency_type', sa.String(length=100), nullable=False),
    sa.Column('impact_level', sa.String(length=50), nullable=False),
    sa.Column('correlation_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blast_radius_id')
    )
    op.create_index(op.f('ix_blast_radius_incident_id'), 'blast_radius', ['incident_id'], unique=False)
    op.create_table('duplicate_identification',
    sa.Column('duplicate_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('matched_incident_id', sa.String(length=36), nullable=False),
    sa.Column('similarity_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('evaluation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('detection_method', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('duplicate_id')
    )
    op.create_index(op.f('ix_duplicate_identification_incident_id'), 'duplicate_identification', ['incident_id'], unique=False)
    op.create_index(op.f('ix_duplicate_identification_matched_incident_id'), 'duplicate_identification', ['matched_incident_id'], unique=False)
    op.create_table('incident_analysis',
    sa.Column('analysis_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('intent_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('severity_prediction', sa.String(length=20), nullable=True),
    sa.Column('severity_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('business_impact', sa.Text(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('next_best_action', sa.Text(), nullable=True),
    sa.Column('root_cause_hypothesis', sa.Text(), nullable=True),
    sa.Column('blast_radius', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('author_input_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('resolution_evaluation_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('recommendation_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('analysis_id')
    )
    op.create_index(op.f('ix_incident_analysis_incident_id'), 'incident_analysis', ['incident_id'], unique=False)
    op.create_table('incident_commanders',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('commander_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['commander_id'], ['commanders.commander_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id', 'commander_id')
    )
    op.create_table('incident_performance_metrics',
    sa.Column('metric_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('war_room_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mttd_seconds', sa.BigInteger(), nullable=True),
    sa.Column('mtta_seconds', sa.BigInteger(), nullable=True),
    sa.Column('mttr_seconds', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_incident_performance_metrics_incident_id'), 'incident_performance_metrics', ['incident_id'], unique=False)
    op.create_table('resolution_intelligence',
    sa.Column('resolution_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('resolver_team', sa.String(length=255), nullable=True),
    sa.Column('resolver_user', sa.String(length=255), nullable=True),
    sa.Column('recommended_resolution', sa.Text(), nullable=True),
    sa.Column('actual_resolution', sa.Text(), nullable=True),
    sa.Column('rollback_recommendation', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('resolution_source', sa.String(length=50), nullable=True),
    sa.Column('resolution_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('resolution_status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resolution_id')
    )
    op.create_index(op.f('ix_resolution_intelligence_incident_id'), 'resolution_intelligence', ['incident_id'], unique=False)
    op.create_table('stakeholder_report',
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=255), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('report_blob_path', sa.String(length=1000), nullable=True),
    sa.Column('notification_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_stakeholder_report_incident_id'), 'stakeholder_report', ['incident_id'], unique=False)
    op.create_index(op.f('ix_stakeholder_report_meeting_id'), 'stakeholder_report', ['meeting_id'], unique=False)
    op.create_table('war_room',
    sa.Column('war_room_id', sa.String(length=36), nullable=False),
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('meeting_id', sa.String(length=255), nullable=True),
    sa.Column('meeting_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript_blob_path', sa.String(length=1000), nullable=True),
    sa.Column('recording_blob_path', sa.String(length=1000), nullable=True),
    sa.Column('logbook_blob_path', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident_master.incident_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('war_room_id')
    )
    op.create_index(op.f('ix_war_room_incident_id'), 'war_room', ['incident_id'], unique=False)
    op.create_table('model_fallback',
    sa.Column('model_execution_id', sa.String(length=36), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('fallback_level', sa.String(length=30), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('latency_ms', sa.BigInteger(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['agent_execution.execution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_execution_id')
    )
    op.create_index(op.f('ix_model_fallback_execution_id'), 'model_fallback', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_fallback_execution_id'), table_name='model_fallback')
    op.drop_table('model_fallback')
    op.drop_index(op.f('ix_war_room_incident_id'), table_name='war_room')
    op.drop_table('war_room')
    op.drop_index(op.f('ix_stakeholder_report_meeting_id'), table_name='stakeholder_report')
    op.drop_index(op.f('ix_stakeholder_report_incident_id'), table_name='stakeholder_report')
    op.drop_table('stakeholder_report')
    op.drop_index(op.f('ix_resolution_intelligence_incident_id'), table_name='resolution_intelligence')
    op.drop_table('resolution_intelligence')
    op.drop_index(op.f('ix_incident_performance_metrics_incident_id'), table_name='incident_performance_metrics')
    op.drop_table('incident_performance_metrics')
    op.drop_table('incident_commanders')
    op.drop_index(op.f('ix_incident_analysis_incident_id'), table_name='incident_analysis')
    op.drop_table('incident_analysis')
    op.drop_index(op.f('ix_duplicate_identification_matched_incident_id'), table_name='duplicate_identification')
    op.drop_index(op.f('ix_duplicate_identification_incident_id'), table_name='duplicate_identification')
    op.drop_table('duplicate_identification')
    op.drop_index(op.f('ix_blast_radius_incident_id'), table_name='blast_radius')
    op.drop_table('blast_radius')
    op.drop_index(op.f('ix_agent_execution_incident_id'), table_name='agent_execution')
    op.drop_table('agent_execution')
    op.drop_index(op.f('ix_incident_master_user_email'), table_name='incident_master')
    op.drop_index(op.f('ix_incident_master_incident_number'), table_name='incident_master')
    op.drop_table('incident_master')
    op.drop_index(op.f('ix_commanders_email'), table_name='commanders')
    op.drop_table('commanders')
    # ### end Alembic commands ###
