"""track commander assignment history

Revision ID: da5cb4114a40
Revises: 5453f4d6ec9f
Create Date: 2026-09-04 17:18:12.024705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da5cb4114a40'
down_revision: Union[str, Sequence[str], None] = '5453f4d6ec9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incident_commanders', sa.Column('incident_commander_id', sa.String(length=36), nullable=False))
    op.add_column('incident_commanders', sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('incident_commanders', sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('incident_commanders', sa.Column('is_primary', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_incident_commanders_commander_id'), 'incident_commanders', ['commander_id'], unique=False)
    op.create_index(op.f('ix_incident_commanders_incident_id'), 'incident_commanders', ['incident_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incident_commanders_incident_id'), table_name='incident_commanders')
    op.drop_index(op.f('ix_incident_commanders_commander_id'), table_name='incident_commanders')
    op.drop_column('incident_commanders', 'is_primary')
    op.drop_column('incident_commanders', 'unassigned_at')
    op.drop_column('incident_commanders', 'assigned_at')
    op.drop_column('incident_commanders', 'incident_commander_id')
    # ### end Alembic commands ###
